/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagement;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.imageio.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.CallableStatement;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.SqlDateModel;

/**
 *
 * @author sksha
 */
public class MainWindowStaff extends javax.swing.JFrame {
    
 Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
String staffName="",gender;
ImageIcon imageIcon=null;
Image image;
static String fid;
ArrayList<String> cid=new ArrayList<>(100);
ArrayList<String> branch=new ArrayList<>(100);
ArrayList<String> section=new ArrayList<>(100);
ArrayList<String> semester=new ArrayList<>(100);
JDatePickerImpl datePicker;
JDatePickerImpl datePickerOut;
ArrayList<Integer> did=new ArrayList<>();

    /**
     * Creates new form MainWindow
     */
    public MainWindowStaff() {
        initComponents();
         conn=JavaConnect.connectDb();
         updateProfile();
         updateHostelGuest();
         updateTeachingCourse();
         datePick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        lbl_staff_id = new java.awt.Label();
        label4 = new java.awt.Label();
        lbl_staff_name = new java.awt.Label();
        label6 = new java.awt.Label();
        lbl_dob = new java.awt.Label();
        label14 = new java.awt.Label();
        lbl_department = new java.awt.Label();
        label16 = new java.awt.Label();
        lbl_designation = new java.awt.Label();
        label18 = new java.awt.Label();
        lbl_ft_pt = new java.awt.Label();
        label20 = new java.awt.Label();
        lbl_specialization = new java.awt.Label();
        jScrollPane_view = new javax.swing.JScrollPane();
        jScrollPane_view.getVerticalScrollBar().setUnitIncrement(16);
        jPanel_view = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        txt_staff_id = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        txt_name = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        txt_dob = new javax.swing.JTextField();
        label13 = new java.awt.Label();
        txt_salary = new javax.swing.JTextField();
        label39 = new java.awt.Label();
        txt_degree = new javax.swing.JTextField();
        label40 = new java.awt.Label();
        txt_department = new javax.swing.JTextField();
        label17 = new java.awt.Label();
        txt_email = new javax.swing.JTextField();
        label19 = new java.awt.Label();
        txt_mobile = new javax.swing.JTextField();
        label21 = new java.awt.Label();
        txt_marital_status = new javax.swing.JTextField();
        label32 = new java.awt.Label();
        txt_aadhar_number = new javax.swing.JTextField();
        label33 = new java.awt.Label();
        txt_house_number = new javax.swing.JTextField();
        label34 = new java.awt.Label();
        txt_street_name = new javax.swing.JTextField();
        label35 = new java.awt.Label();
        txt_city = new javax.swing.JTextField();
        label36 = new java.awt.Label();
        txt_state = new javax.swing.JTextField();
        label37 = new java.awt.Label();
        txt_zip_code = new javax.swing.JTextField();
        label38 = new java.awt.Label();
        txt_country = new javax.swing.JTextField();
        btn_view = new java.awt.Button();
        lbl_image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel20 = new javax.swing.JPanel();
        JPane_hostel_guest = new javax.swing.JScrollPane();
        tbl_hostel_guest = new javax.swing.JTable();
        btn_book_guest_room = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lst_staff_courses = new java.awt.List();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel24 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cb_mark_attendance_class = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cb_mark_attendance_go = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cb_mark_attendance_course = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel_check_in = new javax.swing.JPanel();
        lst_attendance = new java.awt.List();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_submit_attendance = new javax.swing.JButton();
        cb_status = new javax.swing.JComboBox<>();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel26 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cb_result_class = new javax.swing.JComboBox<>();
        cb_result_go = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cb_result_course = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lst_result = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_submit_result = new javax.swing.JButton();
        txt_marks_obtained = new javax.swing.JTextField();
        txt_max_marks = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txt_confirm_password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_new_password = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_logout = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1360, 700));
        setSize(new java.awt.Dimension(1200, 700));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1300, 720));

        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel6.setLayout(new java.awt.GridLayout(11, 2, 10, 0));

        label2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label2.setMaximumSize(new java.awt.Dimension(56, 20));
        label2.setText("Staff ID");
        jPanel6.add(label2);

        lbl_staff_id.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_staff_id.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel6.add(lbl_staff_id);

        label4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label4.setText("Name");
        jPanel6.add(label4);

        lbl_staff_name.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_staff_name.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel6.add(lbl_staff_name);

        label6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label6.setText("DOB");
        jPanel6.add(label6);

        lbl_dob.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_dob.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel6.add(lbl_dob);

        label14.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label14.setText("Department");
        jPanel6.add(label14);

        lbl_department.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_department.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel6.add(lbl_department);

        label16.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label16.setText("Designation");
        jPanel6.add(label16);

        lbl_designation.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_designation.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel6.add(lbl_designation);

        label18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label18.setText("FT/PT");
        jPanel6.add(label18);

        lbl_ft_pt.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_ft_pt.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel6.add(lbl_ft_pt);

        label20.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label20.setText("Specialization");
        jPanel6.add(label20);

        lbl_specialization.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_specialization.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel6.add(lbl_specialization);

        jPanel_view.setMaximumSize(new java.awt.Dimension(788, 400));
        jPanel_view.setLayout(new java.awt.GridLayout(31, 2));

        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setPreferredSize(new java.awt.Dimension(100, 20));
        label3.setText("Staff ID");
        jPanel_view.add(label3);

        txt_staff_id.setEditable(false);
        jPanel_view.add(txt_staff_id);

        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setPreferredSize(new java.awt.Dimension(100, 20));
        label5.setText("Name");
        jPanel_view.add(label5);

        txt_name.setEditable(false);
        jPanel_view.add(txt_name);

        label7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label7.setPreferredSize(new java.awt.Dimension(100, 20));
        label7.setText("DOB");
        jPanel_view.add(label7);

        txt_dob.setEditable(false);
        jPanel_view.add(txt_dob);

        label13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label13.setPreferredSize(new java.awt.Dimension(100, 20));
        label13.setText("Salary");
        jPanel_view.add(label13);

        txt_salary.setEditable(false);
        jPanel_view.add(txt_salary);

        label39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label39.setPreferredSize(new java.awt.Dimension(100, 20));
        label39.setText("Degree");
        jPanel_view.add(label39);

        txt_degree.setEditable(false);
        jPanel_view.add(txt_degree);

        label40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label40.setPreferredSize(new java.awt.Dimension(100, 20));
        label40.setText("Department");
        jPanel_view.add(label40);

        txt_department.setEditable(false);
        jPanel_view.add(txt_department);

        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label17.setPreferredSize(new java.awt.Dimension(100, 20));
        label17.setText("E-mail");
        jPanel_view.add(label17);

        txt_email.setEditable(false);
        jPanel_view.add(txt_email);

        label19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label19.setPreferredSize(new java.awt.Dimension(100, 20));
        label19.setText("Mobile");
        jPanel_view.add(label19);

        txt_mobile.setEditable(false);
        jPanel_view.add(txt_mobile);

        label21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label21.setPreferredSize(new java.awt.Dimension(100, 20));
        label21.setText("Marital Status");
        jPanel_view.add(label21);

        txt_marital_status.setEditable(false);
        jPanel_view.add(txt_marital_status);

        label32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label32.setPreferredSize(new java.awt.Dimension(100, 20));
        label32.setText("Aadhar number");
        jPanel_view.add(label32);

        txt_aadhar_number.setEditable(false);
        jPanel_view.add(txt_aadhar_number);

        label33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label33.setPreferredSize(new java.awt.Dimension(100, 20));
        label33.setText("House number");
        jPanel_view.add(label33);

        txt_house_number.setEditable(false);
        txt_house_number.setToolTipText("");
        jPanel_view.add(txt_house_number);

        label34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label34.setPreferredSize(new java.awt.Dimension(100, 20));
        label34.setText("Street Name");
        jPanel_view.add(label34);

        txt_street_name.setEditable(false);
        txt_street_name.setToolTipText("");
        jPanel_view.add(txt_street_name);

        label35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label35.setPreferredSize(new java.awt.Dimension(100, 20));
        label35.setText("City");
        jPanel_view.add(label35);

        txt_city.setEditable(false);
        txt_city.setToolTipText("");
        jPanel_view.add(txt_city);

        label36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label36.setPreferredSize(new java.awt.Dimension(100, 20));
        label36.setText("State");
        jPanel_view.add(label36);

        txt_state.setEditable(false);
        txt_state.setToolTipText("");
        jPanel_view.add(txt_state);

        label37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label37.setPreferredSize(new java.awt.Dimension(100, 20));
        label37.setText("Zip code");
        jPanel_view.add(label37);

        txt_zip_code.setEditable(false);
        txt_zip_code.setToolTipText("");
        jPanel_view.add(txt_zip_code);

        label38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label38.setPreferredSize(new java.awt.Dimension(100, 20));
        label38.setText("country");
        jPanel_view.add(label38);

        txt_country.setEditable(false);
        txt_country.setToolTipText("");
        jPanel_view.add(txt_country);

        jPanel_view.setVisible(false);

        jScrollPane_view.setViewportView(jPanel_view);

        btn_view.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_view.setLabel("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_image, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(249, 249, 249)
                        .add(btn_view, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 501, Short.MAX_VALUE)
                .add(jScrollPane_view, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 439, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btn_view, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbl_image, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 319, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .add(jScrollPane_view, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Profile", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setMaximumSize(new java.awt.Dimension(1360, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(1360, 700));

        jTabbedPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel20MouseMoved(evt);
            }
        });

        tbl_hostel_guest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JPane_hostel_guest.setViewportView(tbl_hostel_guest);

        btn_book_guest_room.setText("Book Guest Room");
        btn_book_guest_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_book_guest_roomActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel20Layout = new org.jdesktop.layout.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .add(btn_book_guest_room, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 48, Short.MAX_VALUE)
                .add(JPane_hostel_guest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPane_hostel_guest, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
            .add(jPanel20Layout.createSequentialGroup()
                .add(113, 113, 113)
                .add(btn_book_guest_room, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Hostel Guest", jPanel20);

        jTabbedPane2.addTab("Hostel", jTabbedPane4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("You are teaching following courses this time:");

        org.jdesktop.layout.GroupLayout jPanel11Layout = new org.jdesktop.layout.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel11Layout.createSequentialGroup()
                .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel11Layout.createSequentialGroup()
                        .add(383, 383, 383)
                        .add(jLabel2))
                    .add(jPanel11Layout.createSequentialGroup()
                        .add(315, 315, 315)
                        .add(lst_staff_courses, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 487, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(542, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(37, 37, 37)
                .add(lst_staff_courses, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Courses", jPanel11);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cb_mark_attendance_class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_mark_attendance_classMouseClicked(evt);
            }
        });
        cb_mark_attendance_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mark_attendance_classActionPerformed(evt);
            }
        });

        jLabel15.setText("Choose Date:");

        cb_mark_attendance_go.setText("GO!");
        cb_mark_attendance_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mark_attendance_goActionPerformed(evt);
            }
        });

        jLabel14.setText("Choose Course:");

        cb_mark_attendance_course.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mark_attendance_courseItemStateChanged(evt);
            }
        });
        cb_mark_attendance_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_mark_attendance_courseMouseClicked(evt);
            }
        });
        cb_mark_attendance_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mark_attendance_courseActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose Class");

        jPanel_check_in.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_check_in.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel_check_in.setLayout(new java.awt.GridLayout(1, 1));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cb_mark_attendance_class, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel15)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cb_mark_attendance_course, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(98, 98, 98)
                        .add(jPanel_check_in, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cb_mark_attendance_go)
                .add(83, 83, 83))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(cb_mark_attendance_course, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cb_mark_attendance_class, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(22, 22, 22)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel15)
                    .add(jPanel_check_in, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(cb_mark_attendance_go)
                .add(31, 31, 31))
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("status");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Select student");

        btn_submit_attendance.setText("Submit");
        btn_submit_attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submit_attendanceActionPerformed(evt);
            }
        });

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "CR", "CS", "MB", "NA", "NT", "OD", "TL" }));

        org.jdesktop.layout.GroupLayout jPanel24Layout = new org.jdesktop.layout.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel24Layout.createSequentialGroup()
                .add(jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel24Layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel24Layout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 122, Short.MAX_VALUE)
                        .add(lst_attendance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(147, 147, 147)
                .add(jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cb_status, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(84, 84, 84)
                .add(btn_submit_attendance)
                .add(81, 81, 81))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel24Layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(jLabel7)
                .add(18, 18, 18)
                .add(jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lst_attendance, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel24Layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(jPanel24Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .add(jLabel6)
                .add(18, 18, 18)
                .add(jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn_submit_attendance)
                    .add(cb_status, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(348, 348, 348))
        );

        jTabbedPane7.addTab("Mark Attendance", jPanel24);

        jTabbedPane2.addTab("Attendance", jTabbedPane7);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cb_result_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_result_classActionPerformed(evt);
            }
        });

        cb_result_go.setText("GO!");
        cb_result_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_result_goActionPerformed(evt);
            }
        });

        jLabel17.setText("Choose Course:");

        cb_result_course.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_result_courseItemStateChanged(evt);
            }
        });
        cb_result_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_result_courseMouseClicked(evt);
            }
        });

        jLabel8.setText("Choose Class");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel8)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(99, 99, 99)
                                .add(cb_result_go))
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(34, 34, 34)
                                .add(cb_result_class, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cb_result_course, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(57, 57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(cb_result_course, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cb_result_class, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(18, 18, 18)
                .add(cb_result_go)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Max. Marks");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Select student");

        btn_submit_result.setText("Submit");
        btn_submit_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submit_resultActionPerformed(evt);
            }
        });

        txt_marks_obtained.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marks_obtainedActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Marks Obtained");

        org.jdesktop.layout.GroupLayout jPanel26Layout = new org.jdesktop.layout.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel26Layout.createSequentialGroup()
                .add(41, 41, 41)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 51, Short.MAX_VALUE)
                .add(jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel26Layout.createSequentialGroup()
                        .add(lst_result, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(68, 68, 68)
                        .add(jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel26Layout.createSequentialGroup()
                                .add(txt_marks_obtained, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(106, 106, 106))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel26Layout.createSequentialGroup()
                                .add(jLabel11)
                                .add(96, 96, 96)))
                        .add(jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel26Layout.createSequentialGroup()
                                .add(txt_max_marks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(97, 97, 97)
                                .add(btn_submit_result))
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(86, 86, 86))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel26Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lst_result, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel26Layout.createSequentialGroup()
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(jPanel26Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .add(jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel26Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn_submit_result)
                    .add(txt_max_marks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txt_marks_obtained, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(325, 325, 325))
        );

        jTabbedPane8.addTab("Mark Attendance", jPanel26);

        jTabbedPane2.addTab("Result", jTabbedPane8);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 508, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MyActivities", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        txt_confirm_password.setAlignmentX(0.0F);
        txt_confirm_password.setAlignmentY(1.0F);
        txt_confirm_password.setMaximumSize(new java.awt.Dimension(34, 14));
        txt_confirm_password.setMinimumSize(new java.awt.Dimension(34, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("confirm password");
        jLabel4.setAlignmentY(1.0F);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Username");
        jLabel1.setAlignmentY(1.0F);

        lbl_username.setText("user");
        lbl_username.setAlignmentY(1.0F);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("new password");
        jLabel3.setAlignmentY(1.0F);

        txt_new_password.setAlignmentX(0.0F);
        txt_new_password.setAlignmentY(1.0F);
        txt_new_password.setMaximumSize(new java.awt.Dimension(34, 14));
        txt_new_password.setMinimumSize(new java.awt.Dimension(34, 14));

        btn_submit.setText("Submit");

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel4)
                    .add(jLabel3))
                .add(114, 114, 114)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btn_submit)
                    .add(txt_new_password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txt_confirm_password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbl_username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_username)
                    .add(jLabel1))
                .add(29, 29, 29)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_new_password, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3))
                .add(26, 26, 26)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_confirm_password, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(46, 46, 46)
                .add(btn_submit)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(306, 306, 306)
                .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(707, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(49, 49, 49)
                .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Setings", jPanel4);

        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btn_logout.setLabel("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btn_logout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .add(btn_logout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 542, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(292, 292, 292))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        try{
                 String salary,sql="select salary.salary from salary,staffhasDesignation where salary.designation=staffhasdesignation.designation and staffhasdesignation.fid =?";        
         pst=conn.prepareStatement(sql);
         pst.setString(1,fid);
         rs=pst.executeQuery();
         while(rs.next())
         {
             salary=rs.getString("salary");
         }
             //String sql2="select department.dname from studentofdepartment, depaRTMENT WHERE studentofdepartment.did=department.did and studentofdepartment.sid=? ";
         sql="select * from staff where fid =?";        
         pst=conn.prepareStatement(sql);
         pst.setString(1,fid);
         rs=pst.executeQuery();
         while(rs.next())
         {
             String studentId,name,firstName,middleName,lastName,dob,gender,cateogory,admission,degree,ftPt,specialization,section;
             String jeeRollNo,subCateogory,designation,department,semester,minority,email,mobile,maritalStatus,bloodGroup,fathersName,fathersMobile,fathersEmail,mothersName,parentsAnnualIncome,bankAccountNo,bankName,ifscCode,aadharNo,houseNo,streetName,city,state,zipCode,country;
             studentId=fid;
             firstName=rs.getString("FirstName");
             middleName=rs.getString("MiddleName");
             lastName=rs.getString("LastName");
             name=firstName+" "+middleName+" "+lastName;
             dob=rs.getString("DOB");
             department=rs.getString("branch_specialization");
             specialization=rs.getString("degree");
            // designation=rs.getString("designation");
             ftPt="ft";
            
             email=rs.getString("emailid");
             mobile=rs.getString("mobileno");
             maritalStatus=rs.getString("maritalstatus");
            
            
             houseNo=rs.getString("houseno");
             streetName=rs.getString("streetname");
             city=rs.getString("city");
             state=rs.getString("state");
             zipCode="";
             country=rs.getString("country");
             
      
             txt_name.setEditable(false);
             txt_department.setEditable(false);
             
             txt_degree.setEditable(false);
            
             txt_email.setEditable(false);
             txt_mobile.setEditable(false);
             txt_marital_status.setEditable(false);
        
             txt_aadhar_number.setEditable(false);
             txt_house_number.setEditable(false);
             txt_street_name.setEditable(false);
             txt_city.setEditable(false);
             txt_state.setEditable(false);
             txt_zip_code.setEditable(false);
             txt_country.setEditable(false);
             
             txt_email.setBackground(Color.WHITE);
             txt_mobile.setBackground(Color.WHITE);
             txt_marital_status.setBackground(Color.WHITE);
            
             txt_house_number.setBackground(Color.WHITE);
             txt_street_name.setBackground(Color.WHITE);
             txt_city.setBackground(Color.WHITE);
             txt_state.setBackground(Color.WHITE);
             txt_zip_code.setBackground(Color.WHITE);
             txt_country.setBackground(Color.WHITE);
             
            
             txt_name.setText(name);
             txt_dob.setText(dob);
            
             txt_degree.setText(specialization);
           
             txt_email.setText(email);
             txt_mobile.setText(mobile);
             txt_marital_status.setText(maritalStatus);
            // txt_aadhar_number.setText(aadharNo);
             txt_house_number.setText(houseNo);
             txt_street_name.setText(streetName);
             txt_city.setText(city);
             txt_state.setText(state);
             txt_zip_code.setText(zipCode);
             txt_country.setText(country);
              /* show view profile */
          
             jPanel_view.setVisible(true);
                
         }
         }catch(SQLException e)
         {
            JOptionPane.showMessageDialog(null, e);
         }
        
        jPanel_view.setVisible(true);
       // jScrollPane_view.setVisible(true);
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_book_guest_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_book_guest_roomActionPerformed
        // TODO add your handling code here:
         BookHostelForFacultyGuest.main(new String[]{fid});
          updateHostelGuest();
    }//GEN-LAST:event_btn_book_guest_roomActionPerformed

    private void cb_mark_attendance_courseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_mark_attendance_courseItemStateChanged
        // TODO add your handling code here:
            int index;
        if (evt.getStateChange() == ItemEvent.SELECTED && cid.size()!=0){
        index=cb_mark_attendance_course.getSelectedIndex();
        System.out.println(index);
        String sql="{call showClasses(?,?)}";
        try{
            CallableStatement cst;
            cst=conn.prepareCall(sql);
            cst.setString(1, cid.get(index));
            cst.setString(2, fid);
            rs=cst.executeQuery();
            branch.clear();
            section.clear();
            semester.clear();
            cb_mark_attendance_class.removeAllItems();
            while(rs.next())
            {
                String Branch,Section,Semester;
                      Branch=rs.getString("dName");
                       Section=rs.getString("section");
                       Semester =rs.getString("semester");
                       branch.add(Branch);
                       section.add(Section);
                       semester.add(Semester);
                      
                       cb_mark_attendance_class.addItem(Branch+Section+ ", Sem "+Semester);
            }
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"cbMarkAttendance\n"+ ex);
     }
        
    }//GEN-LAST:event_cb_mark_attendance_courseItemStateChanged
    }
    private void cb_mark_attendance_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mark_attendance_goActionPerformed
      int CidIndex=cb_mark_attendance_course.getSelectedIndex();
      int ClassIndex=cb_mark_attendance_class.getSelectedIndex();
        String sql="{call GetStudentsforAttendance(?,?,?,?)}";
        try{
            CallableStatement cst;
            cst=conn.prepareCall(sql);
            cst.setInt(1, Integer.valueOf(cid.get(CidIndex)));
            cst.setInt(2, did.get(ClassIndex));
             cst.setInt(3, Integer.valueOf(section.get(ClassIndex)));
            cst.setInt(4, Integer.valueOf(semester.get(ClassIndex)));
            
            rs=cst.executeQuery();
            lst_attendance.removeAll();
            while(rs.next())
            {
                String sid;
                     sid=rs.getString("sid");
                     lst_attendance.add(sid);
            }
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"cbMarkAttendanceGo\n"+ ex);
     }
    }//GEN-LAST:event_cb_mark_attendance_goActionPerformed

    private void btn_submit_attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submit_attendanceActionPerformed
        String sql="{call after_insert_attendance (?,?,?,?)}";
        java.sql.Date selectedDate = (java.sql.Date) datePicker.getModel().getValue();
        int CidIndex=cb_mark_attendance_course.getSelectedIndex();
     
        CallableStatement cst;
     try {
         cst=conn.prepareCall(sql);
         cst.setString(1, lst_attendance.getSelectedItem());
         cst.setString(2,cid.get(CidIndex));
         cst.setDate(3,selectedDate );
         cst.setString(4,cb_status.getSelectedItem().toString());
         rs=cst.executeQuery();
         JOptionPane.showMessageDialog(null,"OK");
         
     } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"btnSubmitAttendance\n"+ ex);
     }
        
    }//GEN-LAST:event_btn_submit_attendanceActionPerformed

    private void cb_result_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_result_goActionPerformed
        // TODO add your handling code here:
        if(!did.isEmpty()){
            System.out.println("not empty");
        String sql="{call getStudentsforMarks(?,?,?,?)}";
           int index,CidIndex=cb_result_course.getSelectedIndex();
      int ClassIndex=cb_result_class.getSelectedIndex();
       index=cb_result_class.getSelectedIndex();
        try{
            System.out.println("andar");
            CallableStatement cst;
            cst=conn.prepareCall(sql);
            cst.setString(1, cid.get(CidIndex));
            cst.setInt(2, did.get(index));
             cst.setInt(3, Integer.valueOf(section.get(ClassIndex)));
            cst.setInt(4, Integer.valueOf(semester.get(ClassIndex)));
            
            rs=cst.executeQuery();
            lst_result.removeAll();
            while(rs.next())
            {
                String sid;
                     sid=rs.getString("sid");
                     lst_result.add(sid);
            }
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"cbMarkResultGo\n"+ ex);
     }
        }
    }//GEN-LAST:event_cb_result_goActionPerformed

    private void cb_result_courseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_result_courseItemStateChanged
    
    }//GEN-LAST:event_cb_result_courseItemStateChanged

    private void btn_submit_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submit_resultActionPerformed
        String sql="{call after_insert_marks(?,?,?,?)}";
        int CidIndex=cb_result_course.getSelectedIndex();
     
        CallableStatement cst;
     try {
         cst=conn.prepareCall(sql);
         cst.setString(1, lst_result.getSelectedItem());
         cst.setString(2,cid.get(CidIndex));
         cst.setInt(3,Integer.valueOf(txt_marks_obtained.getText()));
         cst.setInt(4,Integer.valueOf(txt_max_marks.getText()));
         rs=cst.executeQuery();
         JOptionPane.showMessageDialog(null,"OK");
         
     } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"btnSubmitAttendance\n"+ ex);
     }
        
    }//GEN-LAST:event_btn_submit_resultActionPerformed

    private void cb_mark_attendance_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_mark_attendance_courseMouseClicked
        // TODO add your handling code here:
         int index;
         index=cb_mark_attendance_course.getSelectedIndex();
        String sql="{call showClasses(?,?)}";
        try{
            CallableStatement cst;
            cst=conn.prepareCall(sql);
            cst.setInt(1, Integer.valueOf(cid.get(index)));
            cst.setString(2, fid);
            rs=cst.executeQuery();
            branch.clear();
            section.clear();
            semester.clear();
            cb_mark_attendance_class.removeAllItems();
            did.clear();
            while(rs.next())
            {
                String Branch,Section,Semester;
                      Branch=rs.getString("Dname");
                       Section=rs.getString("section");
                       Semester =rs.getString("semester");
                      // System.out.println(did);
                       did.add(rs.getInt("did"));
                         System.out.println(did);
                       branch.add(Branch);
                       section.add(Section);
                       semester.add(Semester);
                       cb_mark_attendance_class.addItem(Branch+Section+ ", Sem "+Semester);
            }
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"cbMarkAttendance\n"+ ex);
     }
         
    }//GEN-LAST:event_cb_mark_attendance_courseMouseClicked

    private void cb_mark_attendance_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mark_attendance_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_mark_attendance_classActionPerformed

    private void cb_mark_attendance_classMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_mark_attendance_classMouseClicked
        // TODO add your handling code here:
         int index;
               index=cb_result_course.getSelectedIndex();
        String sql="{call showClasses(?,?)}";
        try{
            CallableStatement cst;
            cst=conn.prepareCall(sql);
            cst.setString(1, cid.get(index));
            cst.setString(2, fid);
            rs=cst.executeQuery();
            branch.clear();
            section.clear();
            semester.clear();
            cb_result_class.removeAllItems();
            while(rs.next())
            {
                String Branch,Section,Semester;
                      Branch=rs.getString("Dname");
                       Section=rs.getString("section");
                       Semester =rs.getString("semester");
                       branch.add(Branch);
                       section.add(Section);
                       semester.add(Semester);
                       cb_result_class.addItem(Branch+Section+ ", Sem "+Semester);
            }
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"cbMarkAttendance\n"+ ex);
     }
         
    }//GEN-LAST:event_cb_mark_attendance_classMouseClicked

    private void cb_result_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_result_courseMouseClicked
        // TODO add your handling code here:
         int index;
             index=cb_result_course.getSelectedIndex();
        String sql="{call showClasses(?,?)}";
        try{
            CallableStatement cst;
            cst=conn.prepareCall(sql);
            cst.setString(1, cid.get(index));
            cst.setString(2, fid);
            rs=cst.executeQuery();
            branch.clear();
            section.clear();
            semester.clear();
            cb_result_class.removeAllItems();
            while(rs.next())
            {
                String Branch,Section,Semester;
                      Branch=rs.getString("Dname");
                       Section=rs.getString("section");
                       Semester =rs.getString("semester");
                       branch.add(Branch);
                       section.add(Section);
                       semester.add(Semester);
                       cb_result_class.addItem(Branch+Section+ ", Sem "+Semester);
            }
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"cbMarkAttendance\n"+ ex);
     }
         
    }//GEN-LAST:event_cb_result_courseMouseClicked

    private void cb_result_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_result_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_result_classActionPerformed

    private void cb_mark_attendance_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mark_attendance_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_mark_attendance_courseActionPerformed

    private void jPanel20MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseMoved
      updateHostelGuest();       
    }//GEN-LAST:event_jPanel20MouseMoved

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
          dispose();
       new LoginWindow().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void txt_marks_obtainedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marks_obtainedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marks_obtainedActionPerformed
private void updateProfile()
     {
         try{
             lbl_username.setText(fid);
             System.out.println("ok man");
             String sql="select * from staff where fid =?";
             //String sql2="select department.dname from studentofdepartment, depaRTMENT WHERE studentofdepartment.did=department.did and studentofdepartment.sid=? ";
                 
         pst=conn.prepareStatement(sql);
         pst.setString(1,fid);
         //pst.setString(2, sid.sid2);
         //pst.setString(3,Integer.toString(sid.sid3));
         rs=pst.executeQuery();
         if(rs.next())
         {
             System.out.println("i ma here");
             String staffId,name,dob,gender,cateogory,department,designation,ftPt,specialization,firstName,middleName,lastName;
             staffId=fid;
             firstName=rs.getString("FirstName");
             middleName=rs.getString("MiddleName");
             lastName=rs.getString("LastName");
             name=firstName+" "+middleName+" "+lastName;
             dob=rs.getString("DOB");
             department=
             specialization=rs.getString("degree");
             cateogory="Gen";
             department=rs.getString("branch_specialization");
             //designation=rs.getString("designation");
             ftPt="FT";
             
            gender="0";
           // gender=String.valueOf(rs.getInt(""));
           lbl_staff_name.setText(name);
           lbl_staff_id.setText(fid);
           lbl_dob.setText(dob);
           lbl_department.setText(department);
          // lbl_designation.setText(designation);
           lbl_ft_pt.setText(ftPt);
           lbl_specialization.setText(specialization);
  
                  

             if(gender.equals("0"))
             {
                 imageIcon = new ImageIcon(getClass().getResource("/collegemanagement/boy_fly.jpg"));
             }
             else
             {
              imageIcon = new ImageIcon(getClass().getResource("/collegemanagement/girl_fly.jpg"));
              }
              image = imageIcon.getImage(); 

              Image newimg = image.getScaledInstance(80, 100,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way 

              imageIcon = new ImageIcon(newimg);
                 lbl_image.setIcon(imageIcon);
         }
         }catch(SQLException e)
         {
            JOptionPane.showMessageDialog(null, "updateProfile()/n"+e);
         }
     }

    private void updateHostelGuest()
     {
         String date,status;
               String sql="SELECT `GuestName`, rooms.RoomNo, rooms.BlockName,hostel.HostelName,`GGender`, `GRelation`, `GContact`, `GPurpose`, `GCheckIn`, `GCheckOut` " +
"FROM `hostel_guests`,books,hostel_guests_in_room,rooms,hostel,roomsinhostel " +
"WHERE hostel_guests.GuestID = books.GuestID and books.BookersID = ? "
                       + " and hostel_guests_in_room.GuestID = books.GuestID "
+ "and rooms.RoomID = hostel_guests_in_room.RoomID and rooms.RoomID = roomsinhostel.RoomID AND roomsinhostel.HostelID = hostel.HostelID";

                try{ 
                  
                        pst=conn.prepareStatement(sql);
                        pst.setString(1, fid);
                        rs=pst.executeQuery();
                        DefaultTableModel model = new DefaultTableModel(new String[]{"ROOM", "HOSTEL","GUEST NAME","RELATION","PURPOSE","CHECK IN","CHECK OUT"}, 0);
                        while(rs.next())
                        {
                           String roomNo,blockName,hostelName,guestName,gRelation,gPurpose,checkIn,checkOut;
                           roomNo=rs.getString("roomno");
                           blockName=rs.getString("blockname");
                           hostelName=rs.getString("HostelName");
                           guestName=rs.getString("GuestName");
                           gRelation=rs.getString("GRelation");
                           gPurpose=rs.getString("GPurpose");
                           checkIn=rs.getString("GCheckIn");
                           checkOut=rs.getString("GCheckOut");
                           model.addRow(new Object[]{blockName+roomNo,hostelName,guestName,gRelation,gPurpose,checkIn,checkOut});
                        }
                        tbl_hostel_guest.setModel(model);
                        tbl_hostel_guest.setDefaultEditor(Object.class,null);
                   }
      catch(SQLException e)
      {
          JOptionPane.showMessageDialog(null,"updateHostelGuest()/n"+ e);
      }
     }
    
    private void updateTeachingCourse()
    {
            String sql="{call getCourses(?)}";
            

                try{ 
                   CallableStatement cst = conn.prepareCall(sql);
                   cst.setString(1,fid);
                   rs=cst.executeQuery();
                      //  DefaultTableModel model = new DefaultTableModel(new String[]{"ROOM", "HOSTEL","SEMESTER"}, 0);
                        while(rs.next())
                        {System.out.println("ho rha h");
                          lst_staff_courses.add(rs.getString("CName"));
                          cb_mark_attendance_course.addItem(rs.getString("CName"));
                          cb_result_course.addItem(rs.getString("CName"));
                          cid.add(rs.getString("cid"));
                       
                        }
                      
                   
      }catch(SQLException e)
      {
          JOptionPane.showMessageDialog(null, "updateTeachingCourse()/n"+e);
      }
    }
     
    private void datePick()
   {
       SqlDateModel modelIn = new SqlDateModel();
       SqlDateModel modelOut = new SqlDateModel();
       JDatePanelImpl datePanelIn,datePanelOut;
       Properties p = new Properties();
p.put("text.today", "Today");
p.put("text.month", "Month");
p.put("text.year", "Year");
        datePanelIn = new JDatePanelImpl(modelIn,p);
        datePanelOut = new JDatePanelImpl(modelOut,p);
       

 
//frame.add(datePicker);
        datePicker = new JDatePickerImpl(datePanelIn,new DateLabelFormatter());
        datePickerOut = new JDatePickerImpl(datePanelOut,new DateLabelFormatter());
         jPanel_check_in.add(datePicker);      
       // jPanel_check_in1.add(datePickerOut);
         revalidate();
         repaint();
       
       

   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      fid=args[0];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JPane_hostel_guest;
    private javax.swing.JButton btn_book_guest_room;
    private java.awt.Button btn_logout;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_submit_attendance;
    private javax.swing.JButton btn_submit_result;
    private java.awt.Button btn_view;
    private javax.swing.JComboBox<String> cb_mark_attendance_class;
    private javax.swing.JComboBox<String> cb_mark_attendance_course;
    private javax.swing.JButton cb_mark_attendance_go;
    private javax.swing.JComboBox<String> cb_result_class;
    private javax.swing.JComboBox<String> cb_result_course;
    private javax.swing.JButton cb_result_go;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_check_in;
    private javax.swing.JPanel jPanel_view;
    private javax.swing.JScrollPane jScrollPane_view;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label3;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label4;
    private java.awt.Label label40;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label lbl_department;
    private java.awt.Label lbl_designation;
    private java.awt.Label lbl_dob;
    private java.awt.Label lbl_ft_pt;
    private javax.swing.JLabel lbl_image;
    private java.awt.Label lbl_specialization;
    private java.awt.Label lbl_staff_id;
    private java.awt.Label lbl_staff_name;
    private javax.swing.JLabel lbl_username;
    private java.awt.List lst_attendance;
    private java.awt.List lst_result;
    private java.awt.List lst_staff_courses;
    private javax.swing.JTable tbl_hostel_guest;
    private javax.swing.JTextField txt_aadhar_number;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_confirm_password;
    private javax.swing.JTextField txt_country;
    private javax.swing.JTextField txt_degree;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_house_number;
    private javax.swing.JTextField txt_marital_status;
    private javax.swing.JTextField txt_marks_obtained;
    private javax.swing.JTextField txt_max_marks;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_new_password;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_staff_id;
    private javax.swing.JTextField txt_state;
    private javax.swing.JTextField txt_street_name;
    private javax.swing.JTextField txt_zip_code;
    // End of variables declaration//GEN-END:variables
}
